---
version: 2.1
jobs:
  irods:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build iRods container
          command: make build_irods

workflows:
  version: 2
  build:
    jobs:
      - irods
